// @ts-nocheck — Legacy data file, replaced by achievementContent.ts
import type { Achievement } from '../types'

export const IMPORTED_ACHIEVEMENTS: Achievement[] = [
  { id: 'import-001', name: '50 блюд', group: 'habits', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-002', name: 'аквариум', group: 'habits', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-003', name: 'амбассадор wfpb', group: 'habits', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-004', name: 'анна в шоке', group: 'habits', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-005', name: 'анна устала', group: 'habits', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-006', name: 'без мяса неделю', group: 'habits', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-007', name: 'без пропусков', group: 'habits', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-008', name: 'без сахара 7 дней', group: 'habits', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-009', name: 'белковый герой', group: 'habits', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-010', name: 'блудный едок', group: 'habits', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-011', name: 'бобовый король', group: 'habits', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-012', name: 'брокколи forever', group: 'habits', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-013', name: 'вдохновитель', group: 'habits', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-014', name: 'весовой контроль', group: 'habits', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-015', name: 'вечерний ритуал', group: 'habits', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-016', name: 'водопад', group: 'habits', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-017', name: 'всё включено', group: 'habits', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-018', name: 'день без критики', group: 'habits', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-019', name: 'детектив тела', group: 'habits', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-020', name: 'диванный эксперт', group: 'habits', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-021', name: 'довел до слез', group: 'habits', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-022', name: 'жаворонок', group: 'habits', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-023', name: 'засуха', group: 'habits', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-024', name: 'зеленая армия', group: 'habits', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-025', name: 'зеркальный день', group: 'habits', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-026', name: 'золотой спин', group: 'habits', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-027', name: 'зомби-режим', group: 'habits', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-028', name: 'идеальная неделя', group: 'habits', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-029', name: 'король майонеза', group: 'habits', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-030', name: 'ледник', group: 'habits', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-031', name: 'любимчик анны', group: 'habits', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-032', name: 'медвежья берлога', group: 'habits', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-033', name: 'месяц чистоты', group: 'habits', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-034', name: 'молчаливое согласие', group: 'habits', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-035', name: 'мясоед упорный', group: 'habits', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-036', name: 'ночная совесть', group: 'habits', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-037', name: 'нулевой мусор', group: 'habits', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-038', name: 'охотник за составом', group: 'habits', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-039', name: 'пророк анны', group: 'habits', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-040', name: 'радуга на завтрак', group: 'habits', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-041', name: 'радуга на тарелке', group: 'habits', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-042', name: 'ранний отбой', group: 'habits', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-043', name: 'рассмешил анну', group: 'habits', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-044', name: 'сахарный преступник', group: 'habits', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-045', name: 'сова крайности', group: 'habits', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-046', name: 'суперфуд-охотник', group: 'habits', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-047', name: 'торт или здоровье', group: 'habits', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-048', name: 'утренний родник', group: 'habits', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-049', name: 'утренний стакан', group: 'habits', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-050', name: 'ферментированный фанат', group: 'habits', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-051', name: 'активность с пользой', group: 'other', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-052', name: 'амбассадор wfpb', group: 'other', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-053', name: 'весовой контроль', group: 'other', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-054', name: 'вдохновитель', group: 'other', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-055', name: 'детектив тела', group: 'other', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-056', name: 'завтрак без спешки', group: 'other', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-057', name: 'золотой спин', group: 'other', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-058', name: 'капелька', group: 'other', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-059', name: 'марафонец', group: 'other', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-060', name: 'минималист', group: 'other', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-061', name: 'на высоте', group: 'other', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-062', name: 'неделя без греха', group: 'other', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-063', name: 'нутри-гений', group: 'other', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-064', name: 'основы wfpb', group: 'other', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-065', name: 'первая тарелка', group: 'other', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-066', name: 'первый шаг', group: 'other', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-067', name: 'поделился', group: 'other', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-068', name: 'светофор здоровья', group: 'other', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-069', name: 'спокойной ночи', group: 'other', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-070', name: 'спринтер', group: 'other', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-071', name: 'сыроед-эксперт', group: 'other', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-072', name: 'сытый старт', group: 'other', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-073', name: 'трансформация', group: 'other', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-074', name: 'читатель этикеток', group: 'other', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-075', name: 'амбассадор wfpb', group: 'other', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-076', name: 'без пропусков', group: 'other', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-077', name: 'блудный едок', group: 'other', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-078', name: 'день без критики', group: 'other', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-079', name: 'золотой спин', group: 'other', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-080', name: 'зеркальный день', group: 'other', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-081', name: 'аквариум', group: 'other', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-082', name: 'капелька', group: 'other', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
  { id: 'import-083', name: 'читатель этикеток', group: 'other', rarity: 'Обычная', xp: 0, unlocked: false, triggerDescription: '', fullDescription: '' },
]
