// @ts-nocheck — Legacy file, replaced by achievementContent.ts
import type { Achievement } from '../types'

export const MOCK_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'onb-1',
    name: 'Первый шаг',
    group: 'onboarding',
    rarity: 'Обычная',
    xp: 10,
    unlocked: true,
    triggerDescription: 'Завершить онбординг и открыть главный экран.',
    fullDescription: 'Ты прошёл первичную настройку профиля и целей здоровья. Теперь курс полностью твой!',
  },
  {
    id: 'water-1',
    name: 'Капелька',
    group: 'water',
    rarity: 'Обычная',
    xp: 10,
    unlocked: true,
    triggerDescription: 'Выпить первую порцию воды (250 мл) за день.',
    fullDescription: 'Гидратация — основа здоровья. Ты сделал первый глоток к своей дневной норме!',
  },
  {
    id: 'water-2',
    name: 'Аквамарин',
    group: 'water',
    rarity: 'Необычная',
    xp: 25,
    unlocked: false,
    triggerDescription: 'Набрать 100% нормы воды 7 дней подряд.',
    fullDescription: 'Целая неделя идеального питьевого режима! Твой организм говорит спасибо.',
  },
  {
    id: 'sleep-1',
    name: 'Спокойной ночи',
    group: 'sleep',
    rarity: 'Обычная',
    xp: 10,
    unlocked: true,
    triggerDescription: 'Заполнить карточку сна впервые.',
    fullDescription: 'Отслеживание сна — ключ к пониманию своего восстановления. Ты на правильном пути!',
  },
  {
    id: 'sleep-2',
    name: 'Гармония Морфея',
    group: 'sleep',
    rarity: 'Редкая',
    xp: 50,
    unlocked: true,
    triggerDescription: 'Спать 7+ часов 14 дней подряд.',
    fullDescription: 'Две недели здорового сна — твой организм восстанавливается, а эндотелий сосудов радуется!',
  },
  {
    id: 'movement-1',
    name: 'Первые шаги',
    group: 'movement',
    rarity: 'Обычная',
    xp: 10,
    unlocked: false,
    triggerDescription: 'Заполнить карточку движения впервые.',
    fullDescription: 'Движение — жизнь! Ты начал отслеживать свою физическую активность.',
  },
  {
    id: 'nutrition-1',
    name: 'Зелёная тарелка',
    group: 'nutrition',
    rarity: 'Обычная',
    xp: 15,
    unlocked: true,
    triggerDescription: 'Добавить первый приём пищи в дневник тарелки.',
    fullDescription: 'Первый шаг к осознанному питанию: ты зафиксировал своё блюдо. Молодец!',
  },
  {
    id: 'nutrition-2',
    name: 'Радуга на тарелке',
    group: 'nutrition',
    rarity: 'Эпическая',
    xp: 80,
    unlocked: false,
    triggerDescription: 'Заполнить 4 разных приёма пищи за один день.',
    fullDescription: 'Завтрак, обед, ужин и перекус — все приёмы пищи учтены. Твой рацион сбалансирован!',
  },
  {
    id: 'digestion-1',
    name: 'Лёгкость бытия',
    group: 'digestion',
    rarity: 'Необычная',
    xp: 25,
    unlocked: false,
    triggerDescription: 'Отметить комфортное пищеварение 5 дней подряд.',
    fullDescription: 'Пять дней без дискомфорта — твой ЖКТ настраивается на здоровый лад!',
  },
  {
    id: 'habits-1',
    name: 'Первая двадцатка',
    group: 'habits',
    rarity: 'Обычная',
    xp: 15,
    unlocked: true,
    triggerDescription: 'Открыть экран «Полезная 20-ка».',
    fullDescription: 'Ты заглянул в список ключевых привычек долголетия. Каждая из них — вклад в здоровье!',
  },
  {
    id: 'habits-2',
    name: 'Ключи здоровья',
    group: 'habits',
    rarity: 'Эпическая',
    xp: 100,
    unlocked: false,
    triggerDescription: 'Заполнить все 20 пунктов «Полезной 20-ки».',
    fullDescription: 'Все двадцать привычек освоены! Ты — настоящий мастер здорового образа жизни.',
  },
  {
    id: 'dishes-1',
    name: 'Кулинарная книга',
    group: 'dishes',
    rarity: 'Обычная',
    xp: 15,
    unlocked: true,
    triggerDescription: 'Сохранить первое блюдо в «Мои блюда».',
    fullDescription: 'Твой личный сборник WFPB-рецептов пополнился первым шедевром!',
  },
  {
    id: 'dishes-2',
    name: 'Шеф-повар',
    group: 'dishes',
    rarity: 'Редкая',
    xp: 50,
    unlocked: false,
    triggerDescription: 'Сохранить 10 блюд в «Мои блюда».',
    fullDescription: 'Десять сохранённых блюд — настоящая кулинарная книга! Ты — WFPB-шеф.',
  },
  {
    id: 'check-1',
    name: 'Детектив состава',
    group: 'check',
    rarity: 'Необычная',
    xp: 25,
    unlocked: true,
    triggerDescription: 'Впервые проверить состав блюда на соответствие WFPB.',
    fullDescription: 'Ты воспользовался проверкой состава — теперь ты точно знаешь, что в твоей тарелке!',
  },
  {
    id: 'recipes-1',
    name: 'Книга долголетия',
    group: 'recipes',
    rarity: 'Необычная',
    xp: 25,
    unlocked: false,
    triggerDescription: 'Открыть «Рецепты долголетия».',
    fullDescription: 'Рецепты долголетия ждут тебя! Здесь собраны лучшие WFPB-варианты для здоровья.',
  },
  {
    id: 'purchases-1',
    name: 'Умный покупатель',
    group: 'purchases',
    rarity: 'Обычная',
    xp: 10,
    unlocked: false,
    triggerDescription: 'Добавить первый продукт в список покупок.',
    fullDescription: 'Список покупок — твой план здорового похода в магазин. Отличное начало!',
  },
  {
    id: 'milestone-1',
    name: 'Первая неделя',
    group: 'milestone',
    rarity: 'Редкая',
    xp: 60,
    unlocked: true,
    triggerDescription: 'Завершить 7 дней курса.',
    fullDescription: 'Целая неделя на курсе! Ты уже заметил первые изменения — продолжай в том же духе.',
  },
  {
    id: 'milestone-2',
    name: 'Полпути',
    group: 'milestone',
    rarity: 'Легендарная',
    xp: 150,
    unlocked: false,
    triggerDescription: 'Достичь 14-го дня курса.',
    fullDescription: 'Экватор! 14 дней позади — половина пути пройдена. Ты невероятно крут!',
  },
]
